### ISSUE TITLE
No user was found with provided ID

### ISSUE THREAD

**Issue by kalebheitzman** [wp-graphql/wp-graphql-jwt-authentication#16]
I login with this mutation

````
mutation LoginUser {
  login(input: {
    username: "admin", 
    password: "admin", 
    clientMutationId: "uniqueId"
  }) {
    authToken
    user {
      id
    }
  }
}
````

Grab the authToken and set it as an Authorization header like so

````
{
  "Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9lcGlzY29tZWRpYS5sb2NhbDo4ODg4IiwiaWF0IjoxNTIxODYwOTAxLCJuYmYiOjE1MjE4NjA5MDEsImV4cCI6MTUyMTg2MTIwMSwiZGF0YSI6eyJ1c2VyIjp7ImlkIjoiMSJ9fX0.y35AkqY7Gj7VzNDJT5_w32YQVytXmuTpnSlfrLUc4SY"
}
````

Run a query for viewer

````
{
  viewer {
    id
  }
}
````

And get the following in results every time

````
{
  "errors": [
    {
      "message": "No user was found with the provided ID",
      "category": "user",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "viewer"
      ]
    }
  ],
  "data": {
    "viewer": null
  }
}
````

I have no idea what I'm doing wrong. I have this plugin enabled and no luck.

**Comment by jasonbahl** [comment]
@kalebheitzman my guess is your setup has something that’s preventing authorization headers from ever making it to WordPress in the first place. 

@michaelcuneo was having a similar issue and we discovered that his local docker setup prevented Auth headers from being passed if there was no SSL. 

He set up a site using Local by Flywheel instead and everything worked great. (Local uses docker behind the scenes but makes it super easy to setup ssl locally, and other cool stuff). 

Anyway, to confirm my theory that Auth headers aren’t making it to your WordPress instance, open your active theme’s functions.php and add the following: 

```
add_action( 'init', function() {
    var_dump( $_SERVER );
    die();
} );
```

Then, in GraphiQL, if your using the desktop app, open dev tools (its a chromium app so command+option+i, if you’re on a Mac). 

With the dev tools open, go to the “network” tab. 

Then, press the play button in GraphiQL to execute your query. 

You should see the request show up in the network tab. Click on it, then click on “results” to see what the request returned. 

What should be returned is the  `$_SERVER` array that we’re var_dumping. 

If you don’t see `HTTP_AUTHORIZATION` in the list with your token, then something is preventing the Auth headers from being sent at all. 

Give it a shot on Local by Flywheel just to see if things are working there. Whether you want to use Local long term or not, is up to you, but it will at least help us rule out if your issue is with WordPress and/or one of these plugins, or if it’s at the network layer. 

I’m on mobile now but can follow up with screenshots showing the debug process a bit more if needed.

**Comment by kalebheitzman** [comment]
@jasonbahl I'll set up local now and check it out. I'm using the latest MAMP Pro to develop. I'll report back on this. Thanks for the info!

**Comment by kalebheitzman** [comment]
I can confirm it's my setup on MAMP Pro. I think this can be closed. An interesting thing to note. When I was testing it with ChromeQL and when I was logged into the site (with a session) it worked. When I logged out it wouldn't. 

Thanks for the help!

**Comment by jasonbahl** [comment]
@kalebheitzman glad to hear it’s working!

Re: Auth in the browser

WordPress naturally tries to authenticate each request using the cookie Auth. So when you’re logged in to WordPress and open a new tab, you’re still authenticated. If you open a new tab and make a request via WP-Admin or WPGraphQL it’s the same WordPress authentication at work. 

If you’re in a decoupled context, like a different domain, the cookie Auth doesn’t work which is why you need another Auth mechanism, such as wp-graphql-jwt-auth (but any of the REST API Auth plugins, like Basic Auth or Oauth work fine with WPGraphQL as well)
