### ISSUE TITLE
registerUser authToken error

### ISSUE THREAD

**Issue by vana-dev** [wp-graphql/wp-graphql-jwt-authentication#90]
this is my mutation:
`mutation registerAndGetToken($username: String!, $password: String!, $email: String!) {
  registerUser(input: {clientMutationId: "", username: $username, email: $email, password: $password}) {
    user {
      jwtAuthToken
      id
    }
  }
}
`

user is registered properly, but I don't receive authToken, Instead I got an error:

> Only the user requesting a token can get a token issued for them

**Comment by jasonbahl** [comment]
@vana-dev My guess is that you had logged in already and had a token that you were sending in your headers, instead of making this request as a public un-authenticated user.

If you passed an `authToken` in the header while making the `registerAndGetToken` mutation, you will get this error as the `registerAndGetToken` mutation is intended for _new_ users to register. 

You can see here where the WP_Error is returned: https://github.com/wp-graphql/wp-graphql-jwt-authentication/blob/d0faaab6cc0dfba47cf111613ad665e7c465e2ff/src/Auth.php#L135

Can you try the request without sending any Auth headers?

**Comment by vana-dev** [comment]
Yes, that is the issue, when I logout form wordpress dashboard, everything work.
